on:
  push:
    branches:
      - main

name: Build

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for Git to git push
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Install Python
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: 3.9
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9
          conda-channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - run: sh scripts/parepare-scikit-image-docs.sh
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "build/scikit-image/doc"
          pre-build-command: "pip install -U pip && pip install scikit-image[docs]==0.21.0 sphinx==6.0 docutils==0.19 babel==2.10 && sed -i 's/buster/oldoldstable/g' /etc/apt/sources.list && apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
          build-command: "make latex && sed -i '/\\documentclass/a \\usepackage[utf8]{inputenc}' build/latex/scikit-image.tex && make latexpdf"
      - run: |
          mkdir -p docs
          cp build/latex/scikit-image.pdf ../../../docs/scikit-image.pdf
      - name: Store docs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./docs