on:
  push:
    branches:
      - main

name: Build

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for Git to git push
    name: Build
    runs-on: ubuntu-latest
    env:
      SCIKIT_IMAGE_VERSION: 0.21.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Install Python
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: 3.9
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9
          conda-channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Try to download compiled scikit-image.pdf file
        id: download-file
        run: mkdir -p docs && wget https://oeway.github.io/hypha-knowledge-base/scikit-image-$SCIKIT_IMAGE_VERSION.pdf -O docs/scikit-image-$SCIKIT_IMAGE_VERSION.pdf && echo "::set-output name=file_exists::true" || echo "::set-output name=file_exists::false"
      - run: sh scripts/parepare-scikit-image-docs.sh
        if: steps.download-file.outputs.file_exists == 'true'
      - uses: ammaraskar/sphinx-action@master
        if: steps.download-file.outputs.file_exists == 'true'
        with:
          docs-folder: "build/scikit-image/doc"
          pre-build-command: "pip install -U pip && pip install scikit-image[docs]==$SCIKIT_IMAGE_VERSION sphinx==6.0 docutils==0.19 babel==2.10 && sed -i 's/buster/oldoldstable/g' /etc/apt/sources.list && apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
          build-command: "make latexpdf-fixed"
        continue-on-error: true
      - name: Collect pdf
        if: steps.download-file.outputs.file_exists == 'true'
        run: |
          mkdir -p docs
          cp build/scikit-image/doc/build/latex/scikit-image.pdf docs/scikit-image-$SCIKIT_IMAGE_VERSION.pdf
      - name: Build vector database
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          python scripts/build_vector_database.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
